language: ruby

services:
  - mysql

before_script:
  - cp config/.travis.database.yml config/database.yml
  - bin/rails db:setup RAILS_ENV=test

script:
  - bundle exec rspec

notifications:
  slack: techcamp-tokyo-st:O20NFqzyKle2viWwgyMm6yzf
